apiVersion: apps/v1
kind: Deployment

metadata:
  name: cloud-devops-app
  namespace: cloud-devops

spec:
  replicas: 2

  selector:
    matchLabels:
      app: cloud-devops-app

  template:
    metadata:
      labels:
        app: cloud-devops-app

    spec:
      containers:
        - name: cloud-devops-app
          image: sree2627/cloud-devops-project:latest

          ports:
            - containerPort: 80

          env:
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: cloud-devops-config
                  key: APP_NAME

            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: cloud-devops-config
                  key: ENVIRONMENT

            - name: APP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: cloud-devops-secret
                  key: APP_USERNAME

            - name: APP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloud-devops-secret
                  key: APP_PASSWORD

          volumeMounts:
            - name: app-data
              mountPath: /usr/share/nginx/html/data

      volumes:
        - name: app-data
          emptyDir: {}

